// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6Yj2_1V7RjME-LeZ0qItRrurcHk9Z9U',
    appId: '1:627318819573:web:b93d79b0c1c6050872d3bc',
    messagingSenderId: '627318819573',
    projectId: 'together-2',
    authDomain: 'together-2.firebaseapp.com',
    storageBucket: 'together-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP8OKPW9LMo7KTysZ6rChPTLeuZRGeGxw',
    appId: '1:627318819573:android:239a775d081903c572d3bc',
    messagingSenderId: '627318819573',
    projectId: 'together-2',
    storageBucket: 'together-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXZ2eU41BF1vVtT6GWl6VPWTUTdSPyMA0',
    appId: '1:627318819573:ios:663b5ef57a9218ad72d3bc',
    messagingSenderId: '627318819573',
    projectId: 'together-2',
    storageBucket: 'together-2.appspot.com',
    iosBundleId: 'com.example.togetherVersion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXZ2eU41BF1vVtT6GWl6VPWTUTdSPyMA0',
    appId: '1:627318819573:ios:663b5ef57a9218ad72d3bc',
    messagingSenderId: '627318819573',
    projectId: 'together-2',
    storageBucket: 'together-2.appspot.com',
    iosBundleId: 'com.example.togetherVersion2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6Yj2_1V7RjME-LeZ0qItRrurcHk9Z9U',
    appId: '1:627318819573:web:59c42317de62251672d3bc',
    messagingSenderId: '627318819573',
    projectId: 'together-2',
    authDomain: 'together-2.firebaseapp.com',
    storageBucket: 'together-2.appspot.com',
  );

}